<?php

// generated by updateConfig.php on 06/12/2016 00:16(Europe/Paris time)

require_once realpath(dirname(dirname(__FILE__))).'/vendor/autoload.php';
use Monolog\Logger;
if (! isset($_SESSION)) session_start();

// global setting
$_SESSION['ENVIRONMENT'] = 'HOMO';
$_SESSION['MERCHANT_ID'] = '40227288250349';
$_SESSION['MERCHANT_NAME'] = "FRIIIO";
$_SESSION['ACCESS_KEY'] = 'zJKQwcHf7QKI9gw0Ag9s';
$_SESSION['ACCESS_KEY_REF'] = 'test';
$_SESSION['WS_VERSION'] = '0';
$_SESSION['PROXY_HOST'] = '';
$_SESSION['PROXY_PORT'] = '';
$_SESSION['PROXY_LOGIN'] = '';
$_SESSION['PROXY_PASSWORD'] = '';

// demo settings
$_SESSION['KIT_ROOT'] = 'https://cookorico.com/';
$_SESSION['LOG_PATH'] = '/var/www/html/dist/api/payline';
$_SESSION['LOG_LEVEL'] = Logger::DEBUG;

// payment setting
$_SESSION['PAYMENT_CURRENCY'] = '978';
$_SESSION['ORDER_CURRENCY'] = '978';
$_SESSION['LANGUAGE_CODE'] = 'fi';
$_SESSION['PAYMENT_ACTION'] = '100';
$_SESSION['PAYMENT_MODE'] = '001';
$_SESSION['CUSTOM_PAYMENT_TEMPLATE_URL'] = '';
$_SESSION['CUSTOM_PAYMENT_PAGE_CODE'] = '';
$_SESSION['CONTRACT_NUMBER'] = '1234567';
$_SESSION['CONTRACT_NUMBER_LIST'] = '';
$_SESSION['SECOND_CONTRACT_NUMBER_LIST'] = '';
$_SESSION['WALLET_CONTRACT_NUMBER_LIST'] = '';
$_SESSION['RETURN_URL'] = 'http://localhost:1234';
$_SESSION['NOTIFICATION_URL'] = '';
$_SESSION['CANCEL_URL'] = 'http://localhost:1234';

// buyer info
$_SESSION['buyerLegalStatus'] = '';
$_SESSION['buyerTitle'] = '';
$_SESSION['buyerLastName'] = "Scarabin";
$_SESSION['buyerFirstName'] = "Emmanuel";
$_SESSION['buyerEmail'] = 'scarabin.emmanuel@gmail.com';
$_SESSION['billingAddressTitle'] = "";
$_SESSION['billingAddressFirstName'] = "";
$_SESSION['billingAddressLastName'] = "";
$_SESSION['billingAddressName'] = "";
$_SESSION['billingAddressStreet1'] = "";
$_SESSION['billingAddressStreet2'] = "";
$_SESSION['billingAddressCity'] = "";
$_SESSION['billingAddressZipCode'] = '';
$_SESSION['billingAddressCountry'] = "";
$_SESSION['billingAddressCounty'] = "";
$_SESSION['billingAddressState'] = "";
$_SESSION['billingAddressPhoneType'] = '';
$_SESSION['billingAddressPhone'] = '';
$_SESSION['shippingAddressTitle'] = '';
$_SESSION['shippingAddressFirstName'] = "";
$_SESSION['shippingAddressLastName'] = "";
$_SESSION['shippingAddressName'] = "";
$_SESSION['shippingAddressStreet1'] = "";
$_SESSION['shippingAddressStreet2'] = "";
$_SESSION['shippingAddressCity'] = "";
$_SESSION['shippingAddressZipCode'] = '';
$_SESSION['shippingAddressCountry'] = "";
$_SESSION['shippingAddressCounty'] = "";
$_SESSION['shippingAddressState'] = "";
$_SESSION['shippingAddressPhoneType'] = '';
$_SESSION['shippingAddressPhone'] = '';
$_SESSION['buyerAccountCreateDate'] = '';
$_SESSION['buyerAverageAmount'] = '';
$_SESSION['buyerOrderCount'] = '';
$_SESSION['buyerWalletId'] = "";
$_SESSION['buyerWalletDisplayed'] = '';
$_SESSION['buyerWalletSecured'] = '';
$_SESSION['buyerWalletCardInd'] = '';
$_SESSION['buyerIp'] = '';
$_SESSION['mobilePhone'] = '';
$_SESSION['customerId'] = "";
$_SESSION['legalDocument'] = '';
$_SESSION['birthDate'] = '';
$_SESSION['fingerprintID'] = "";
$_SESSION['deviceFingerprint'] = "";
$_SESSION['isIncognito'] = '';
$_SESSION['isBot'] = '';
$_SESSION['isBehindProxy'] = '';
$_SESSION['isFromTor'] = '';
$_SESSION['isEmulator'] = '';
$_SESSION['isRooted'] = '';
$_SESSION['hasTimezoneMismatch'] = '';
?> 
